# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e5a6173ee1d6ca1188509acbc953884f8f67e6248a82d63bb3f5b039e5a3cc85ad1732a6115401a88df42a6429e06429d1d6420881fab75f7d2372fab57212

test:
  secret_key_base: 61b72c4750415fc1e66039b1425c470500e0168c629d7a6e9c04fc4686139376874d23ccae30d2a21723652a79d45d0915a4ca89c026434ecfd4104c6a608399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
